import { motion } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import { ButtonLink } from '../ui/Button';
import { SectionHeading } from '../ui/SectionHeading';
import { GALLERY_ITEMS } from '../../data/gallery';
import { asset } from '../../lib/assets';

export function GalleryTeaser() {
  const featured = GALLERY_ITEMS.slice(0, 4);
  return (
    <section className="mx-auto max-w-7xl px-4 py-24 sm:px-6">
      <SectionHeading
        eyebrow="Specimens"
        title="Fresh from the synthesis chamber"
        description="Real outputs generated by the model — no cherry-picked renders, just 64×128 pixels of pure block magic."
      />
      <div className="mt-14 grid grid-cols-2 gap-4 lg:grid-cols-4">
        {featured.map((item, i) => (
          <motion.figure
            key={item.id}
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.45, delay: i * 0.08 }}
            className="group glass relative overflow-hidden rounded-2xl"
          >
            <img
              src={asset(item.image)}
              alt={item.caption}
              loading="lazy"
              className="w-full transition-transform duration-500 group-hover:scale-[1.04]"
            />
            <figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-void/90 to-transparent px-4 pt-10 pb-3 font-mono text-xs uppercase tracking-wider text-ink/90">
              {item.title}
            </figcaption>
          </motion.figure>
        ))}
      </div>
      <div className="mt-10 text-center">
        <ButtonLink to="/gallery" variant="secondary">
          View the full gallery
          <ArrowRight className="h-4 w-4" aria-hidden="true" />
        </ButtonLink>
      </div>
    </section>
  );
}
