import { usePageTitle } from '../hooks/usePageTitle';
import { GalleryGrid } from '../components/gallery/GalleryGrid';
import { GridBackground } from '../components/ui/GridBackground';

export function GalleryPage() {
  usePageTitle('Gallery');
  return (
    <div className="relative overflow-hidden">
      <GridBackground />
      <div className="relative mx-auto max-w-6xl px-4 pt-28 pb-24 sm:px-6">
        <header className="max-w-2xl">
          <p className="font-mono text-xs font-medium uppercase tracking-[0.25em] text-primary">
            Specimen archive
          </p>
          <h1 className="mt-3 font-display text-4xl font-bold tracking-tight">Gallery</h1>
          <p className="mt-3 text-muted">
            Every image below was generated by the model — real 64×128 outputs from real input photos.
            Click any specimen to inspect it up close.
          </p>
        </header>
        <div className="mt-10">
          <GalleryGrid />
        </div>
      </div>
    </div>
  );
}
