import { usePageTitle } from '../hooks/usePageTitle';

// Content ported from the original site's terms.html.
const sections: Array<{ title: string; paragraphs: string[] }> = [
  {
    title: '1. Introduction',
    paragraphs: [
      'Welcome to LegofyNet. This project is educational and non-commercial, aiming to explore image processing technologies to generate artistic visualizations inspired by building-block figures.',
      'By accessing this website, you agree to comply with these terms and conditions. If you do not agree with any of the terms outlined here, please refrain from using this website.',
    ],
  },
  {
    title: '2. Intellectual Property',
    paragraphs: [
      'All content generated by users, including uploaded images, remains the property of their respective authors. Images generated on this site are temporary and not stored. This is an independent site not authorized or sponsored by the LEGO® Group or Lucasfilm Ltd., and the generated images are not exact copies of official products.',
    ],
  },
  {
    title: '3. Website Usage',
    paragraphs: [
      'The use of this website is free, without the need for registration or any kind of transaction. It is solely for educational and research purposes.',
    ],
  },
  {
    title: '4. Privacy Policy',
    paragraphs: [
      'LegofyNet does not collect, store, or process any personal data. No cookies are used, and no personal information such as names or email addresses is requested.',
      'Uploaded images are neither transferred nor stored on external servers; all processing — including the AI model itself — runs locally in your browser.',
    ],
  },
  {
    title: '5. Educational and Research Purposes',
    paragraphs: [
      'This project is for educational purposes only, with no intention of generating profit. Its purpose is to explore generative methods and image processing technologies.',
    ],
  },
  {
    title: '6. Limitation of Liability',
    paragraphs: [
      'LegofyNet is provided "as is," without any guarantees, either express or implied. We do not take responsibility for technical errors, bugs, or interruptions to the website\'s availability.',
    ],
  },
  {
    title: '7. Modifications to the Terms',
    paragraphs: [
      'We reserve the right to modify these terms at any time, with changes becoming effective once published on this page.',
    ],
  },
  {
    title: '8. Governing Law and Jurisdiction',
    paragraphs: [
      'These terms are governed by and interpreted in accordance with the laws of Spain and the European Union. Any disputes arising from the use of this website will be subject to the jurisdiction of the courts of Spain.',
    ],
  },
  {
    title: '9. User-Generated Content and AI-Generated Images',
    paragraphs: [
      'All images generated through LegofyNet are based on input provided by users. The creator of this website does not take any responsibility for the images generated from user-provided input. The generated content is solely the responsibility of the user who provided the input image, and LegofyNet is not liable for any misuse or copyright violations that may arise from user-generated content.',
    ],
  },
  {
    title: '10. Use of Third-Party Images',
    paragraphs: [
      'LegofyNet uses images sourced from third-party websites strictly for educational and non-commercial purposes. Images marked "Editorial Use Only" are not used in advertising, promotional material, or any context involving fees or commercial transactions. This website is not affiliated with, sponsored, authorized, or endorsed by the LEGO® Group, and all custom content or modifications are independent of the LEGO Group\'s endorsement or responsibility.',
      'Furthermore, all images displayed on the site have been generated by artificial intelligence models and do not replicate or copy any existing commercial or copyrighted material. They serve only as educational and experimental examples.',
    ],
  },
];

export function TermsPage() {
  usePageTitle('Terms & Privacy');
  return (
    <div className="mx-auto max-w-3xl px-4 pt-28 pb-24 sm:px-6">
      <header>
        <p className="font-mono text-xs font-medium uppercase tracking-[0.25em] text-primary">Legal</p>
        <h1 className="mt-3 font-display text-4xl font-bold tracking-tight">
          Terms of Service & Privacy Policy
        </h1>
      </header>
      <div className="mt-10 space-y-10">
        {sections.map((section) => (
          <section key={section.title}>
            <h2 className="font-display text-xl font-semibold">{section.title}</h2>
            {section.paragraphs.map((p, i) => (
              <p key={i} className="mt-3 text-sm leading-relaxed text-muted">
                {p}
              </p>
            ))}
          </section>
        ))}
      </div>
    </div>
  );
}
