import type { GalleryItem } from '../types';

// Real outputs generated by the model, showcased on the original site.
export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'yoda',
    image: 'images/gallery/yoda.png',
    title: 'Yoda',
    caption: 'Portrait transformed with the Yoda class.',
    classId: 'yoda',
  },
  {
    id: 'darth-vader',
    image: 'images/gallery/darth-vader.png',
    title: 'Darth Vader',
    caption: 'Generated with the Darth Vader class.',
    classId: 'darth-vader',
  },
  {
    id: 'mandalorian',
    image: 'images/gallery/mandalorian.png',
    title: 'Mandalorian',
    caption: 'Armored output from the Mandalorian class.',
    classId: 'mandalorian',
  },
  {
    id: 'togruta',
    image: 'images/gallery/togruta.png',
    title: 'Togruta',
    caption: 'Vivid head-tail patterns from the Togruta class.',
    classId: 'togruta',
  },
  {
    id: 'imperial-soldier',
    image: 'images/gallery/imperial-soldier.png',
    title: 'Imperial Soldier',
    caption: 'Military tones from the Imperial Soldier class.',
    classId: 'imperial-soldier',
  },
  {
    id: 'diego-portrait',
    image: 'images/gallery/diego-portrait.png',
    title: 'Founder portrait',
    caption: "The project founder's own photo, legofied.",
  },
];
